version: '3'
services:
  webapp:
    container_name: webapp
    build: .
    restart: always
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./uploads:/uploads
    # command: "docker-php-ext-install mysqli"
  mysql:
    container_name: database_server
    image: mariadb
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: qwerty
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: qwerty
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment: 
      PMA_HOST: database_server

